import "./styles/reset.scss"
import './styles/globals.scss'
import './styles/classes.scss'
import './styles/changedDaisyComponents.scss'

import type { Metadata } from 'next'
import {Abhaya_Libre} from 'next/font/google'
import Navbar from "@/app/components/navbar/Navbar";
import {AuthContextProvider} from "@/app/context/AuthContext";

const Abhaya = Abhaya_Libre(
    {
      weight:["400", "500", "600", "700", "800"],
      subsets:["latin"]}
)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="bg-secondary"  data-theme="cupcake" lang="en">
      <body className={`${Abhaya.className}`}>
      <AuthContextProvider>
          <Navbar/>
          {children}
      </AuthContextProvider>
      </body>
    </html>
  )
}
